### PR TITLE
Fixing command execution in external windows for both mac and win platforms 

### PR DESCRIPTION
**Pull request by mcopjan**
- Upgrade to netCore 2.2 was necessary as 2.0 is not being supported any more
- Windows command had to be modified as it was not working for paths containing white spaces
- Directory.GetCurrentDirectory() does not work on Mac platform, it was changed to use reflection instead

### CODE REVIEW

**Comment by mcopjan** [comment]
Looks like the box building PR does not contain Net.Core 2.2 SDK I would like to stick with this (latest) version but I can downgrade if you want me to.

**Comment by mcopjan** [comment]
used travis changes for netcore 2.2 described at https://travis-ci.community/t/dotnet-core-2-2/1216/5

**Comment by mcopjan** [comment]
@equiman Hi Camilo, any update on this please?

**Review by equiman — CHANGES_REQUESTED** [review]
This file has not significant changes. Could you please remove from PR?

**Review by equiman — COMMENTED** [review]
Why ToolBox.userprefs has been removed?

**Review by equiman — COMMENTED** [review]
Whats the reason to change it and use reflection?
Have you some kind of trouble with Directory.GetCurrentDirectory()?

**Review by equiman — COMMENTED** [review]
Cool that TAGS on global. I didn't know about it. 
Thanks!

**Comment by equiman** [comment]
> Why ToolBox.userprefs has been removed?

Now I see. It's and user preference file created by VS for mac.

**Comment by mcopjan** [comment]
> This file has not significant changes. Could you please remove from PR?

**Pull request closed without merging**
